#!/usr/bin/env python3
"""Extract representative Rust examples so documentation edits are compiled."""
import argparse
from pathlib import Path
import re
import sys
import subprocess

ROOT = Path(__file__).resolve().parent.parent
DESTINATION = ROOT / "compatibility/alpha20/src/examples.rs"

def blocks(relative):
    return re.findall(r"```rust\n(.*?)```", (ROOT / relative).read_text(), re.S)

def matching(relative, prefix):
    matches = [block for block in blocks(relative) if prefix in block]
    if len(matches) != 1:
        raise ValueError(f"Expected one {prefix!r} block in {relative}")
    return matches[0]

def generate():
    sections = [
        "// Generated by scripts/generate-alpha20-examples.py; edit the source examples.\n",
        "pub mod error {\n" + matching("skills/architecture/references/error-mapping.md", "pub enum AppError") + "}\n",
        "pub use error::AppError;\n",
        "pub mod settings {\n"
        + matching("skills/configuration/references/fragments.md", "pub struct MyAppSettings")
        + matching("skills/configuration/references/fragments.md", "impl SettingsValidation") + "}\n",
        "pub use settings::MyAppSettings;\n",
        matching("skills/signals/references/testing-signals.md", "async fn signal_dispatch_is_observed"),
        matching("skills/signals/references/testing-signals.md", "async fn enqueue_records_pending_work"),
        "use crate::receiver::{MockOrderRepo, OrderDto, SendOrderConfirmation};\n"
        "use reinhardt::tasks::{TaskError, TaskExecutor};\n"
        "use std::sync::{Arc, atomic::{AtomicU32, Ordering}};\n"
        "use uuid::Uuid;\nuse mockall::predicate::eq;\n",
        matching("skills/signals/references/testing-signals.md", "async fn order_confirmation_uses_the_injected_repository"),
        matching("skills/signals/references/testing-signals.md", "async fn order_confirmation_records_delivery_once"),
        matching("skills/signals/references/testing-signals.md", "async fn order_confirmation_rejects_missing_orders"),
    ]
    return subprocess.run(
        ["rustfmt", "--edition", "2024", "--emit", "stdout"],
        input="\n".join(sections), capture_output=True, text=True, check=True,
    ).stdout

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = generate()
    if args.check:
        if not DESTINATION.is_file() or DESTINATION.read_text() != expected:
            print("Compatibility examples are stale; run scripts/generate-alpha20-examples.py", file=sys.stderr)
            return 1
    else:
        DESTINATION.write_text(expected)
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
