// Generated by scripts/generate-alpha20-examples.py; edit the source examples.

pub mod error {
    use hyper::StatusCode;
    use reinhardt::{Error, http::Response};
    use serde::Serialize;

    #[derive(Debug, thiserror::Error)]
    pub enum AppError {
        #[error("{0}")]
        NotFound(String),
        #[error("{0}")]
        Validation(String),
        #[error("{0}")]
        PermissionDenied(String),
        #[error("{0}")]
        Conflict(String),
        #[error("{0}")]
        Unauthorized(String),
        #[error(transparent)]
        Framework(#[from] Error),
    }

    impl AppError {
        pub fn status_code(&self) -> StatusCode {
            match self {
                Self::NotFound(_) => StatusCode::NOT_FOUND,
                Self::Validation(_) => StatusCode::BAD_REQUEST,
                Self::PermissionDenied(_) => StatusCode::FORBIDDEN,
                Self::Conflict(_) => StatusCode::CONFLICT,
                Self::Unauthorized(_) => StatusCode::UNAUTHORIZED,
                Self::Framework(error) => StatusCode::from_u16(error.status_code())
                    .unwrap_or(StatusCode::INTERNAL_SERVER_ERROR),
            }
        }

        pub fn error_response(&self) -> reinhardt::Result<Response> {
            let detail = match self {
                Self::Framework(_) => match self.status_code() {
                    StatusCode::BAD_REQUEST => "Invalid request",
                    StatusCode::UNAUTHORIZED => "Authentication required",
                    StatusCode::FORBIDDEN => "Permission denied",
                    StatusCode::NOT_FOUND => "Resource not found",
                    StatusCode::CONFLICT => "Request conflict",
                    StatusCode::SERVICE_UNAVAILABLE => "Service unavailable",
                    _ => "Internal server error",
                },
                Self::NotFound(message)
                | Self::Validation(message)
                | Self::PermissionDenied(message)
                | Self::Conflict(message)
                | Self::Unauthorized(message) => message,
            };
            Response::new(self.status_code()).with_json(&serde_json::json!({ "detail": detail }))
        }
    }

    pub fn http_result<T: Serialize>(
        result: Result<T, AppError>,
        success_status: StatusCode,
    ) -> reinhardt::Result<Response> {
        match result {
            Ok(value) => Response::new(success_status).with_json(&value),
            Err(error) => error.error_response(),
        }
    }
}

pub use error::AppError;

pub mod settings {
    use reinhardt::settings;
    use serde::{Deserialize, Serialize};

    #[settings(fragment = true, section = "myapp", validate = false)]
    #[derive(Clone, Debug, Serialize, Deserialize)]
    pub struct MyAppSettings {
        pub api_key: String,
        pub max_retries: u32,
        #[serde(default = "default_timeout")]
        pub timeout_secs: u64,
    }

    fn default_timeout() -> u64 {
        30
    }
    use reinhardt::conf::settings::{
        fragment::SettingsValidation,
        profile::Profile,
        validation::{ValidationError, ValidationResult},
    };

    impl SettingsValidation for MyAppSettings {
        fn validate(&self, profile: &Profile) -> ValidationResult {
            if self.max_retries == 0 {
                return Err(ValidationError::InvalidValue {
                    key: "myapp.max_retries".into(),
                    message: "must be greater than zero".into(),
                });
            }
            if self.timeout_secs > 300 {
                return Err(ValidationError::Constraint(
                    "myapp.timeout_secs must be at most 300".into(),
                ));
            }
            if *profile == Profile::Production && self.api_key.starts_with("dev-") {
                return Err(ValidationError::Security(
                    "production myapp.api_key must not use a development key".into(),
                ));
            }
            if self.api_key.is_empty() {
                return Err(ValidationError::MissingRequired("myapp.api_key".into()));
            }
            Ok(())
        }
    }
}

pub use settings::MyAppSettings;

use reinhardt::core::signals::{Signal, SignalSpy};
use rstest::rstest;

#[rstest]
#[tokio::test]
async fn signal_dispatch_is_observed() {
    // Arrange
    let signal = Signal::<i32>::new_with_string("test_order_saved");
    let spy = SignalSpy::<i32>::new();
    signal.add_middleware(spy.clone());

    // Act
    signal.send(42).await.unwrap();

    // Assert
    assert_eq!(spy.call_count(), 1);
}

use reinhardt::tasks::{DurableQueue, JobEventKind, JobSpec, JobState, SqliteDurableJobStore};

#[rstest]
#[tokio::test]
async fn enqueue_records_pending_work() {
    // Arrange
    let store = SqliteDurableJobStore::new("sqlite::memory:").await.unwrap();
    let queue = DurableQueue::new(store);

    // Act
    let queued = queue.enqueue(JobSpec::new("send_email")).await.unwrap();
    let persisted = queue.status(queued.id).await.unwrap();
    let events = queue.events(queued.id).await.unwrap();

    // Assert
    assert_eq!(persisted.state, JobState::Queued);
    assert_eq!(events.len(), 1);
    assert_eq!(events[0].kind, JobEventKind::Enqueued);
}

use crate::receiver::{MockOrderRepo, OrderDto, SendOrderConfirmation};
use mockall::predicate::eq;
use reinhardt::tasks::{TaskError, TaskExecutor};
use std::sync::{
    Arc,
    atomic::{AtomicU32, Ordering},
};
use uuid::Uuid;

#[rstest]
#[tokio::test]
async fn order_confirmation_uses_the_injected_repository() {
    // Arrange
    let order_id = Uuid::now_v7();
    let mut repository = MockOrderRepo::new();
    repository
        .expect_get()
        .with(eq(order_id))
        .times(1)
        .returning(|id| {
            Ok(Some(OrderDto {
                id,
                notification_sent: false,
            }))
        });
    repository
        .expect_mark_notified()
        .with(eq(order_id))
        .times(1)
        .returning(|_| Ok(()));
    let repository = Arc::new(repository);
    let task = SendOrderConfirmation::new(order_id, Arc::clone(&repository));

    // Act
    task.execute().await.unwrap();

    // Assert
    // Dropping the last mock owner verifies both exact call expectations.
    drop(task);
    drop(repository);
}

#[rstest]
#[tokio::test]
async fn order_confirmation_records_delivery_once() {
    // Arrange
    let order_id = Uuid::now_v7();
    let recorded = Arc::new(AtomicU32::new(0));
    let read_count = Arc::clone(&recorded);
    let write_count = Arc::clone(&recorded);
    let mut repository = MockOrderRepo::new();
    repository
        .expect_get()
        .with(eq(order_id))
        .times(2)
        .returning(move |id| {
            Ok(Some(OrderDto {
                id,
                notification_sent: read_count.load(Ordering::SeqCst) > 0,
            }))
        });
    repository
        .expect_mark_notified()
        .with(eq(order_id))
        .times(1)
        .returning(move |_| {
            write_count.fetch_add(1, Ordering::SeqCst);
            Ok(())
        });
    let task = SendOrderConfirmation::new(order_id, Arc::new(repository));

    // Act
    task.execute().await.unwrap();
    task.execute().await.unwrap();

    // Assert
    assert_eq!(recorded.load(Ordering::SeqCst), 1);
}

#[rstest]
#[tokio::test]
async fn order_confirmation_rejects_missing_orders() {
    // Arrange
    let order_id = Uuid::now_v7();
    let mut repository = MockOrderRepo::new();
    repository
        .expect_get()
        .with(eq(order_id))
        .times(1)
        .returning(|_| Ok(None));
    repository.expect_mark_notified().times(0);
    let task = SendOrderConfirmation::new(order_id, Arc::new(repository));

    // Act
    let error = task.execute().await.unwrap_err();

    // Assert
    match error {
        TaskError::ExecutionFailed(message) => assert_eq!(message, "Order not found"),
        other => panic!("Unexpected task error: {other}"),
    }
}
